name: C/C++ CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout submodules
      uses: actions/checkout@v2
      with:
        args: git submodule update --init --recursive
    - name: build
      run: make build
    - name: test
      run: ./build/mytests
