name: C/C++ CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: checkout submodules
      uses: textbook/git-checkout-submodule-action@2.1.1
    - name: build
      run: make build
    - name: test
      run: ./build/mytests
